In [1]:
import numpy as np
import math

R = np.diag([1.2,2.3,4.2])
R
speed_profile = [2.0] * 3
speed_profile
move_direction = math.atan2(1.0, 0.0)
move_direction

1.5707963267948966

In [9]:

c = np.random.randn(3,4) # 生成标准正态分布。均值为0，方差为1

c.shape

print(c)


[[-0.51202084 -0.26447207 -0.88193734 -0.09781247]
 [-0.37113883 -0.9446504  -0.04857926 -0.64503919]
 [ 0.56493048  1.69813349 -0.40286165 -0.94312859]]


In [11]:
# Import packages.
import cvxpy as cp
import numpy as np

# Generate a random non-trivial linear program.
m = 15
n = 10
np.random.seed(1)
s0 = np.random.randn(m)
lamb0 = np.maximum(-s0, 0)
s0 = np.maximum(s0, 0)
print(s0)
print("----")
x0 = np.random.randn(n)
A = np.random.randn(m, n)
b = A@x0 + s0
c = -A.T@lamb0

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(c.T@x),
                 [A@x <= b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)

[1.62434536 0.         0.         0.         0.86540763 0.
 1.74481176 0.         0.3190391  0.         1.46210794 0.
 0.         0.         1.13376944]
----

The optimal value is -15.220912604404832
A solution x is
[-1.1015836  -0.16207264 -0.90072437  0.03042621  0.61108486 -1.13141957
  1.1270734   0.87833368  0.48871908  0.89807117]
A dual solution is
[2.45894208e-09 6.11756417e-01 5.28171745e-01 1.07296862e+00
 6.38551602e-09 2.30153871e+00 1.12756160e-09 7.61206895e-01
 1.31943038e-08 2.49370376e-01 2.02551464e-09 2.06014070e+00
 3.22417209e-01 3.84054335e-01 2.94504008e-09]


In [12]:
import numpy as np
import cvxpy as cp

# paramater
c = np.array([-40,-50])
A = np.array([
    [1,3],
    [2,1]
])
b = np.array([12,10])

# cost function
x = cp.Variable(c.shape[0])
constrains = [A@x <= b]
prob = cp.Problem(cp.Minimize(c.T@x), constrains)
prob.solve()

# result
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)


The optimal value is -284.0
A solution x is
[3.6 2.8]
A dual solution is
[12. 14.]
